spring.config.import=optional:file:.env[.properties]

spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:\
  ${POSTGRES_PORT:5432}/${POSTGRES_DB:fitcubes_db}
spring.datasource.username=${POSTGRES_USER:postgres}
spring.datasource.password=${POSTGRES_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.open-in-view=false
spring.jpa.defer-datasource-initialization=false
spring.jpa.hibernate.ddl-auto=validate

spring.data.redis.host=${REDIS_HOST:localhost}
spring.data.redis.port=${REDIS_PORT:6379}
spring.data.redis.password=${REDIS_PASSWORD:}

management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=always

spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml

jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION:86400000}

app.cors.allowed-origins=${FRONTEND_URL:http://localhost:3000}
